### PR TITLE
Fix undefined method send_data (resolves #14)

### LINKED ISSUE #14: Undefined method send_data using batches
Since the update to statsd 2.0, the following error is present:

```
[7] pry(main)> s.batch do |b|
[7] pry(main)*   b.increment('hi')
[7] pry(main)* end  
NoMethodError: undefined method `send_data' for #<Statsd::Client:0x007fccf40e3da0>
```

Note this doesn't break the existing functionality:
```
[8] pry(main)> s.increment('hi')
=> true
```

### PR DESCRIPTION
**Pull request by relwell**
For some reason, ::Statsd::Client doesn't like a bare invocation of send_data. This fixes it by wrapping @send_data in a send_data method that invokes it.  Let's merge this after @avalade's change is in.

### CODE REVIEW

**Comment by relwell** [comment]
This looks like a spurious failure. I'm investigating.

**Comment by relwell** [comment]
Oh yeah, this: https://github.com/lookout/statsd/issues/6

**Comment by smathieu** [comment]
🚢

**Comment by relwell** [comment]
Same bug, different build. Can someone retrigger? @smathieu ?

**Comment by ismith** [comment]
I'll retrigger.

**Pull request merged**
