### PR TITLE
Inject dependent variables from Statsd Client to Batch

### PR DESCRIPTION
**Pull request by relwell**
We can't seem to use forwardable to rely on the Statsd
values we want.

Update batching documentation to describe correct
invocation of gauge, which takes a single hash and not two
arguments.

### CODE REVIEW

**Comment by smathieu** [comment]
I don't see why this is a problem. Can you provide a bit more details about why forwardable isn't working in this case?

**Comment by relwell** [comment]
My guess here is that this has to do with Statsd::Client using instance variables instead of bare names for its variables. One thing I should probably add in here are some tests I can show fail without this and pass with it.

**Comment by relwell** [comment]
Test:
```
describe Statsd::Batch do
  let(:c) { Statsd::Client.new :host => 'foo.com', :prefix => 'my.app.', :port => 1234, :batch_size => 20 }

  it 'should delegate fields correctly' do
    c.batch do |b|
      expect(b.host).to eql 'foo.com'
      expect(b.prefix).to eql 'my.app.'
      expect(b.port).to eql 1234
      expect(b.batch_size).to eql 20
    end
  end

  describe '#gauge' do
    it 'should apply the prefix correctly' do
      c.batch do |b|
        b.should_receive(:send_stats).with(["my.app.an_incrementer:2|g"])
        b.gauge({'an_incrementer' => 2})
      end
    end
  end
end
```

Results:
```
thq-m-relwe02:statsd relwell$ bundle exec rspec spec
...........................F

Failures:

  1) Statsd::Batch#gauge should apply the prefix correctly
     Failure/Error: b.gauge({'an_incrementer' => 2})
       #<Statsd::Batch:0x007fec2e19a1f0> received :send_stats with unexpected arguments
         expected: (["my.app.an_incrementer:2|g"])
              got: (["an_incrementer:2|g"])
     # ./lib/statsd.rb:78:in `gauge'
     # ./spec/statsd_spec.rb:230:in `block (4 levels) in <top (required)>'
     # ./lib/statsd.rb:199:in `easy'
     # ./lib/statsd.rb:103:in `batch'
     # ./spec/statsd_spec.rb:228:in `block (3 levels) in <top (required)>'
```

I can fix this one of two ways:
1) Dependency-inject every value from statsd into the batch (most backwards-compatible)
2) Remove the instance-variable @ in statsd (I think this introduces risk)

**Comment by relwell** [comment]
I've also added more thorough tests here to avoid any more surprises.

**Comment by relwell** [comment]
@smathieu @ismith this looks like that spurious instantiation failure again. @avalade heads up that my attempt to fix that didn't work and your PR should get merged as well. can someone retrigger?

**Comment by ismith** [comment]
Retriggering.

**Comment by relwell** [comment]
Anything else we need to do to get this one merged?

**Pull request merged**
